require("user.option")
require("user.plugins")
require("user.misc")
require("user.lualine")
require("user.keymaps")
require("user.cmp")
require("user.lsp")
require("user.telescope")
require("user.treesitter")
require("user.autopairs")
require("user.comment")
require("user.gitsigns")
require("user.nvimtree")
require("user.bufferline")
require("user.git")
-- require("user.symoutline")
require("user.toggleterm")
require("user.project")
require("user.impatient")
require("user.alpha")
-- require("user.navic")
require("user.illuminate")
require("user.dap")
require("user.ufo")
require("user.autocommands")
-- require("user.whichkey")
-- require("user.wilder")
require("user.saga")
require("user.indentline")
require("user.coderun")
require("user.hlslens")
require("user.neoscroll")
require("user.bookmark")
require("user.noice")
